server:
  port: 3000

spring:
    application:
        name: jpalocks
    config:
        import: optional:secret.properties
        # activate:
        #     on-profile: dev
    profiles:
        active: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/jpalocks
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
      show-sql: true
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: validate
      properties.hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  #     ddl-auto: create-drop # This tells Hibernate to recreate the database on startup.
    #     ddl-auto: validate # in testing or production databases

#logging:
#  level:
#    org.flywaydb: DEBUG
