spring:
  application:
    name: transaction-2-phase-commit
#  datasource:
#    user_ds:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5439/user_db
#      username: postgres
#      password: postgres123
#    order_ds:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5440/order_db
#      username: postgres
#      password: postgres123
#  jta:
#    enabled: true
#    defaultTimeout: 60000


user.db:
  url: jdbc:mysql://localhost:3306/user_db?pinGlobalTxToPhysicalConnection=true
  username: user
  passport: user123
order.db:
  url: jdbc:postgresql://localhost:5440/order_db
  username: order
  passport: order123

---
