version: '3.3'

networks:
  cqrs-network:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    networks:
      - cqrs-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - cqrs-network
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userdb
    ports:
      - ${POSTGRES_PORT:-5439}:5432
    networks:
      - cqrs-network

  cqrs-ms-user-command-service:
    platform: linux/amd64 #Required for Mac M1 PRO
    build: ./cqrs-ms-user-command-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - KAFKA_TOPIC_NAME=com.example.cqrs.ms.users.json
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.hsqldb.jdbc.JDBCDriver
      - SPRING_DATASOURCE_URL=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - kafka
    networks:
      - cqrs-network
  cqrs-ms-user-query-service:
    platform: linux/amd64 #Required for Mac M1 PRO
    build: ./cqrs-ms-user-query-service
    ports:
      - '8080:8080'
    environment:
      - KAFKA_TOPIC_NAME=com.example.cqrs.ms.users.json
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - kafka
      - db
    networks:
      - cqrs-network
