version: '3.3'

networks:
  app-network:
    driver: bridge

services:
  user_db:
    image: mysql:9.0.1
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - ./dockerInitDb/docker-entrypoint-initdb.d.user:/docker-entrypoint-initdb.d
  order_db:
    image: postgres:16.1
    container_name: order_db
    environment:
      - POSTGRES_PASSWORD=order123
      - POSTGRES_USER=order
      - POSTGRES_DB=order_db
    ports:
      - ${POSTGRES_PORT:-5440}:5432
    volumes:
      - ./dockerInitDb/docker-entrypoint-initdb.d.order:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
