version: "3.3"

#volumes:
#  pg_data:

networks:
  jpalocks:

services:

  pg_db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=jpalocks
#    volumes:
#      - pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - jpalocks
